config/routes.rb
Rails.application.routes.draw do
  root to: 'forms#index'

  resources :forms, except: [:index]

  get '/services', to: "pages#services"
  get '/team', to: "pages#team"
  get '/contact', to: "pages#contact"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  def index
    @forms = Form.all
  end

  # GET /forms/1
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  def create
    @form = Form.new(form_params)

    if @form.save
      redirect_to @form, notice: 'Form was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /forms/1
  def update
    if @form.update(form_params)
      redirect_to @form, notice: 'Form was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /forms/1
  def destroy
    @form.destroy
    redirect_to root_path, notice: 'Form was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def form_params
      params.require(:form).permit(:name, :last_name, :phone_number, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def services
end

def team
end

def contact
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/forms/_form.html.erb
<%= simple_form_for(@form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Nombre' %>
    <%= f.input :last_name, label: 'Apellido'  %>
    <%= f.input :phone_number, label: 'Celular'  %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Enviar' %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', root_path %>

app/views/forms/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="https://phenomenon-innovation-lab.herokuapp.com/">
    <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615847946/Phenomenon_logo_blanco_tknrzr.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/services">Servicios</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/team">Portafolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/forms/new">Acerca de</a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  id="navbarTextImp" href="https://wa.me/message/ESS3U564JJOGP1">Trabajemos juntos</a>
      </li>
    </ul>
  </div>
</div>






<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1621989808/bg_hero_l64gli.jpg);">
  <div class="container">
    <div class= "value-prop">
      <div>
         <p>x Enrutamos sueños</p>
      </div>
      <div>
         <p>x Creemos en tus proyectos</p>
      </div>
    </div>
    <h1 id="banner-title">Fuimos creados para crear</h1>
  </div>
</div>


<div class="value-proposition-container">
  <div class="image-value-prop">
    <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1625012452/bg_texture_1_2x_z5accv.jpg" alt="Girl in a jacket" width="412" height="648">
  </div>
  <div class="value-prop-home">
    <div class="organize-value-prop-image">

      <div class="white-space-image-top">

      </div>
      <div class="value-prop-image-top">
         <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1625012956/bg_texture_2_2x_gqbzvq.png" alt="Marketing" width="513" height="70">
      </div>

    </div>

    <div class="value-prop-text">
      <p>Phenomenon es una compañía <strong> incubadora de innovación </strong>cuyo propósito es apoyar a los emprendedores colombianos a crear marcas  que generen impacto en entornos digitales.</p>


      <p>Creemos en el potencial de los proyectos de nuestros clientes y hemos llegado para ser partícipes del crecimiento de sus sueños.  </p>

      <p id="blue-text-value-prop">Phenomenon</p>

    </div>

    <div class="story-telling">
      <div class="story-telling-squares">
        <h2>02</h2>
        <p>Somos nativos<br> digitales</p>
      </div>
      <div class="story-telling-squares">
        <h2>03</h2>
        <p>Damos vida a <br> un Phenomeno</p>
      </div>
      <div class="story-telling-squares">
        <h2>04</h2>
        <p>Aliados de <br> emprendedores</p>
      </div>
      <div class="story-telling-squares">
        <h2>05</h2>
        <p>Desarrollamos proyectos<br> con impacto</p>
      </div>
      <div class="story-telling-squares">
        <h2>06</h2>
        <p>Cambiemos Colombia <br> juntos</p>
      </div>
    </div>

  </div>

</div>

<div class="blueLine">

</div>


<div class="ourServices">
  <h4>Nuestros Servicios</h4>
  <h3>Somos el paquete completo</h3>
</div>

<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615859116/cj-dayrit-xX2aYSBsyKo-unsplash_aaxefk.jpg);">
  <div class="card-container">
    <div class= "button-card">
      <a class="btn btn-flat" href="#">Diseño</a>

    </div>
    <div class="button-card-two">
      <a class="btn btn-flat" href="#">web</a>
    </div>
  </div>
</div>

<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615859562/tyler-lastovich-8_LZ9UWTKLE-unsplash_jesd4m.jpg);">
  <div class="card-container">
    <div class= "button-card">
      <a class="btn btn-flat" href="#">Mercadeo</a>

    </div>
    <div class="button-card-two">
      <a class="btn btn-flat" href="#">Digital</a>
    </div>
  </div>
</div>

<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615859691/rafael-leao-hpOrvWRNJLo-unsplash_gfewyw.jpg);">
  <div class="card-container">
    <div class= "button-card">
      <a class="btn btn-flat" href="#">Desarrollo de</a>

    </div>
    <div class="button-card-two">
      <a class="btn btn-flat" href="#">marca</a>
    </div>
  </div>
</div>


<div class="master-projects">

  <div class="home-proyectos">
    <div class="top-bar-projects">
      <div class="top-bar-projects-text">
        <h4><span style="color:#0017FF">Proyectos </span>recientes</h4>
      </div>
      <div class="top-bar-projects-image">
      <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1625012956/bg_texture_2_2x_gqbzvq.png" alt="Girl in a jacket" width="513" height="70">
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-lg-4">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1618800161/random-institute-QmxXYlyYgL8-unsplash_kh0bb6.jpg" width="100%" height="100%" />
      </div>

      <div class="col-sm-6 col-lg-4">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1618800161/random-institute-QmxXYlyYgL8-unsplash_kh0bb6.jpg" width="100%" height="100%" />
      </div>

      <div class="col-sm-6 col-lg-4">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1618800161/random-institute-QmxXYlyYgL8-unsplash_kh0bb6.jpg" width="100%" height="100%" />
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-lg-4">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1618800161/random-institute-QmxXYlyYgL8-unsplash_kh0bb6.jpg" width="100%" height="100%" />
      </div>

      <div class="col-sm-6 col-lg-4">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1618800161/random-institute-QmxXYlyYgL8-unsplash_kh0bb6.jpg" width="100%" height="100%" />
      </div>

      <div class="col-sm-6 col-lg-4">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1618800161/random-institute-QmxXYlyYgL8-unsplash_kh0bb6.jpg" width="100%" height="100%" />
      </div>
    </div>
  </div>

</div>


<div class="master-projects">

  <div class="home-proyectos">
    <div class="top-bar-projects">
      <div class="top-bar-projects-text">
        <h4><span style="color:#0017FF">Nuestro </span>equipo</h4>
      </div>
      <div class="top-bar-projects-image">
      <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1625012956/bg_texture_2_2x_gqbzvq.png" alt="Girl in a jacket" width="513" height="70">
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-lg-3">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1627957738/nicolas_p4ogkm.jpg" width="100%" height="100%" />
      </div>

      <div class="col-sm-6 col-lg-3">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1627957743/susana_muxy8d.jpg" width="100%" height="100%" />
      </div>

      <div class="col-sm-6 col-lg-3">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1627957740/simon_t9na4h.jpg" width="100%" height="100%" />
      </div>


      <div class="col-sm-6 col-lg-3">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1627957737/marco_jm6fsg.jpg" width="100%" height="100%" />
      </div>
    </div>
  </div>

</div>






<div class="footer-master-banner">
      <div class="banner-footer" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1622392442/bg_footer_wcltee.jpg);">
        <div class="container-footer">
          <div class="top-line-footer">
            <div class="logo-phenomenon">
              <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615847946/Phenomenon_logo_blanco_tknrzr.png" />
              <p>La incubadora de diseño de tus sueños</p>
            </div>
            <div>
            </div>
            <div class="contact-footer">
              <h4>Contactanos</h4>
              <p>co.phenomenon@gmail.com</p>
              <p>+57 3133910480</p>
            </div>
            <div>
               <li class="nav-item">
                  <a class="nav-link"  id="navbarTextImp" href="https://wa.me/message/ESS3U564JJOGP1">Trabajemos juntos</a>
                </li>
            </div>
          </div>
          <div class="white-line-master">
            <div class="whiteLineFooter">
            </div>
          </div>
          <div class="boton-line-footer">
            <div>
              <p>© 2021 Phenomenon</p>
            </div>
            <div class="footer-links">
                <a href="https://www.instagram.com/phenomenon.innovation.lab/?hl=es-la"><i class="fab fa-instagram"></i></a>
                <a href="https://www.facebook.com/Phenomenon-Innovation-Lab-103465388445735"><i class="fab fa-facebook-square"></i></a>
                <a href="https://wa.me/message/ESS3U564JJOGP1"><i class="fab fa-whatsapp"></i></a>
              </div>
          </div>
        </div>
      </div>

</div>

app/views/forms/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="https://phenomenon-innovation-lab.herokuapp.com/">
    <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615847946/Phenomenon_logo_blanco_tknrzr.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/services">Servicios</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/team">Portafolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/forms/new">Acerca de</a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  id="navbarTextImp" href="https://wa.me/message/ESS3U564JJOGP1">Trabajemos juntos</a>
      </li>
    </ul>
  </div>
</div>


<div class="banner-team" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615934909/Artboard_2_xzpyau.png);">
  <div class="container-team">
    <h3 id="team-title">Fuimos creados para crear</h3>
    <h1>Contáctanos</h1>
    <div class="whiteLine">
    </div>
  </div>
</div>

<div class="contact-picture" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1618800161/random-institute-QmxXYlyYgL8-unsplash_kh0bb6.jpg);">
  <div class="container">
    <div class= "button-banner">
    </div>
  </div>
</div>






<div class = "form">
  <h1>Headquarters</h1>
  <h2>Bogotá, Colombia</h2>
  <%= render 'form', form: @form %>

</div>


<div class="master-banner">
      <div class="banner-footer" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615934909/Artboard_2_xzpyau.png);">
      <div class="container-footer">
        <h1 id="footer-title">¡Trabajemos juntos!</h1>
        <h3>Contáctanos y dejanos saber lo que estas buscando y nuestro experto en el tema se pondrá en contacto contigo.</h3>
        <div class= "button-banner">
          <a class="btn btn-footer" href="https://wa.me/message/ESS3U564JJOGP1">Contáctanos</a>
        </div>
        <div class="whiteLine">
        </div>
        <div class="footer">
          <div>
            <h1>Phenomenon</h1>
            <p>La incubadora de diseño</p>
            <p>Derechos reservados ℗</p>
          </div>
          <div class="footer-links-cont">
            <p>Contáctanos</p>
            <div class="footer-links">
              <a href="https://www.instagram.com/phenomenon.innovation.lab/?hl=es-la"><i class="fab fa-instagram"></i></a>
              <a href="https://www.facebook.com/Phenomenon-Innovation-Lab-103465388445735"><i class="fab fa-facebook"></i></a>
              <a href="https://wa.me/message/ESS3U564JJOGP1"><i class="fab fa-whatsapp"></i></a>
            </div>
          </div>
        </div>
      </div>
</div>

</div>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @form.name %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @form.last_name %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @form.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @form.email %>
</p>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phenomenon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100;0,300;0,700;0,800;1,100;1,300;1,700;1,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&family=IBM+Plex+Sans:wght@600&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" id="navbarText" href="#">Servicios</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="#">Equipo</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="#">Contáctanos</a>
      </li>
    </ul>
  </div>
</div>


<div class="banner-team" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615934909/Artboard_2_xzpyau.png);">
  <div class="container-team">
    <h3 id="team-title">Fuimos creados para crear</h3>
    <h1>Contáctanos</h1>
    <div class="whiteLine">
    </div>
  </div>
</div>

<div class="contact-picture" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1618608863/Bogota_Headquarters_pyat0s.jpg);">
  <div class="container">
    <div class= "button-banner">
    </div>
  </div>
</div>

app/views/pages/services.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="https://phenomenon-innovation-lab.herokuapp.com/">
    <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615847946/Phenomenon_logo_blanco_tknrzr.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/services">Servicios</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/team">Portafolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/forms/new">Acerca de</a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  id="navbarTextImp" href="https://wa.me/message/ESS3U564JJOGP1">Trabajemos juntos</a>
      </li>
    </ul>
  </div>
</div>

app/views/pages/team.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="https://phenomenon-innovation-lab.herokuapp.com/">
    <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615847946/Phenomenon_logo_blanco_tknrzr.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/services">Servicios</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/team">Portafolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="navbarText" href="https://phenomenon-innovation-lab.herokuapp.com/forms/new">Acerca de</a>
      </li>
      <li class="nav-item">
        <a class="nav-link"  id="navbarTextImp" href="https://wa.me/message/ESS3U564JJOGP1">Trabajemos juntos</a>
      </li>
    </ul>
  </div>
</div>

<div class="banner-team" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615934909/Artboard_2_xzpyau.png);">
  <div class="container-team">
    <h3 id="team-title">Fuimos creados para crear</h3>
    <h1>Nuestros Socios</h1>
    <div class="whiteLine">
    </div>
  </div>
</div>


<div class="team-member">
  <div class="team-name">
    <div>
      <h1>Susana Garcés</h1>
    </div>
    <div>
      <h1>></h1>
    </div>
    <div>
      <p>Psicologa & Diseñadora</p>
    </div>
  </div>

   <div class="member-details">

      <div class="member-photo">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/v1619616017/SGCB_N_kkejmk.jpg" />
      </div>
      <div>
        <p>Susana es egresada de la Universidad de los Andes y hace parte de la clase de 2021 del Master en Experiencia del Consumidor e Innovacion de la universidad IE en España. Ha trabajado con McCANN Erickson como ejecutiva de cuenta junior de una marca colombiana de retail. Susana es apasionada por el comportamiento humano y fascinada con encontrar soluciones creativas y relevantes a las circunstancias reales del mundo. Quiere encontrar el significado detrás de las marcas que llegan a Phenomenon para desde ahí ayudarlas a dejar una huella en el mundo. </p>
      </div>
    </div>
</div>


<div class="team-member">
  <div class="team-name">
    <div>
      <h1>Simón Martinez</h1>
    </div>
    <div>
      <h1>></h1>
    </div>
    <div>
      <p>Administrador & Desarrollador Web</p>
    </div>
  </div>

   <div class="member-details">

      <div class="member-photo">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/e_grayscale/v1619372168/LinkedIn_nbnosw.jpg" />
      </div>
      <div>
        <p>Simón es líder de Special Projects en Rappi. Su profesión es Administrador de Empresas del CESA y Full Stack Web Developer, estuvo en Madrid haciendo el Le Wagon Coding Bootcamp. Tiene experiencia desarrollando productos web, e-commerce y mínimos productos viables para probar ideas. Es apasionado por los productos digitales que generan impacto en la vida de las personas.
Ahora busca ayudar a nuestros clientes a desarrollar sus negocios en entornos digitales e impulsar el éxito de los emprendedores colombianos.  </p>
      </div>
    </div>
</div>

<div class="team-member">
  <div class="team-name">
    <div>
      <h1>Nicolás Gutierrez</h1>
    </div>
    <div>
      <h1>></h1>
    </div>
    <div>
      <p>Diseñador Grafico & Publicista</p>
    </div>
  </div>

   <div class="member-details">

      <div class="member-photo">
        <img src="https://res.cloudinary.com/dlj1mjxjd/image/upload/c_scale,w_2840/v1619370962/_GTR3031_copy_kgsh6x.jpg" />
      </div>
      <div>
        <p>Diseñador gráfico y Publicista de la universidad de Bogotá Jorge Tadeo Lozano. Ha sido jefe de diseño de revista Arcadia, revista Semana Sostenible y Semana Educación, también fue parte del equipo de diseño de Revista Semana. Ha estado vinculado a las agencias Estudio Codesign, Keep Agency y a la agencia de branding española Pastrana. Actualmente es diseñador pedagógico de la UBPD (Unidad de Búsqueda de Personas Desaparecidas) y director de diseño de Tell. Nicolás cuenta con más de 5 años de experiencia en los campos del diseño editorial, el diseño de marca y la ilustración. Recientemente fue integrado dentro del Portafolio de Collagistas Colombianos para su edición del 2020.</p>
      </div>
    </div>
</div>

<div class="master-banner">
      <div class="banner-footer" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dlj1mjxjd/image/upload/v1615934909/Artboard_2_xzpyau.png);">
      <div class="container-footer">
        <h1 id="footer-title">¡Trabajemos juntos!</h1>
        <h3>Contáctanos y dejanos saber lo que estas buscando y nuestro experto en el tema se pondrá en contacto contigo.</h3>
        <div class= "button-banner">
          <a class="btn btn-footer" href="https://wa.me/message/ESS3U564JJOGP1">Contáctanos</a>
        </div>
        <div class="whiteLine">
        </div>
        <div class="footer">
          <div>
            <h1>Phenomenon</h1>
            <p>La incubadora de diseño</p>
            <p>Derechos reservados ℗</p>
          </div>
          <div class="footer-links-cont">
            <p>Contáctanos</p>
            <div class="footer-links">
              <a href="https://www.instagram.com/phenomenon.innovation.lab/?hl=es-la"><i class="fab fa-instagram"></i></a>
              <a href="https://www.facebook.com/Phenomenon-Innovation-Lab-103465388445735"><i class="fab fa-facebook"></i></a>
              <a href="https://wa.me/message/ESS3U564JJOGP1"><i class="fab fa-whatsapp"></i></a>
            </div>
          </div>
        </div>
      </div>
</div>

</div>